pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    workingDir: ./tests/
    command: custom
    customCommand: 'ci'

- task: Npm@1
  displayName: 'npm test chrome'
  inputs:
    workingDir: ./tests/
    command: custom
    customCommand: 'run test:ci'

- task: Bash@3
  displayName: 'npm install puppeteer firefox'
  inputs:
    targetType: 'inline'
    workingDirectory: ./tests/
    script: PUPPETEER_PRODUCT=firefox npm install puppeteer@3.0.0

- task: Bash@3
  displayName: 'npm test firefox'
  inputs:
    targetType: 'inline'
    workingDirectory: ./tests/
    script: PUPPETEER_PRODUCT=firefox npm run test:ci
