pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    workingDir: ./tests/
    command: custom
    customCommand: 'ci'

- task: Npm@1
  displayName: 'npm test'
  inputs:
    workingDir: ./tests/
    command: custom
    customCommand: 'run test:ci'
